<table>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th colspan="2">Action</th>
    </tr>
    <?php
    $collection = $block->getResult();
    foreach ($collection as $item) {
    ?> <tr>
            <td><?php echo $item->getData('post_id'); ?></td>
            <td><?php echo $item->getData('name'); ?></td>
            <td><?php echo $item->getData('created_at'); ?></td>
            <td><?php echo $item->getData('updated_at'); ?></td>
            <td><a href="<?php echo $block->getUrl('helloworld/index/edit') . 'id/' . $item->getData('post_id'); ?>" class="action primary">Edit</a></td>
            <td><a href="<?php echo $block->getUrl('helloworld/index/delid') . '?id=' . $item->getData('post_id'); ?>" class="action primary">Delete</a></td>
        </tr>
    <?php } ?>
</table>
<a class="action primary" href="<?php echo $block->getUrl('helloworld/index/create'); ?>">Add Record</a>
<a class="action primary" href="<?php echo $block->getUrl('helloworld/index/delete'); ?>">Delete All Record</a>