<?php

$customerID = 1;
$_customerOrder = $block->getOrderCollectionByCustomerId($customerID);

foreach ($_customerOrder as $_order) {

    $arr = $_order->getData();

    echo '<b>Store name:</b> ' . $arr['store_name'] . '<br>';
    echo '<b>Entity Id:</b> '.$arr['entity_id'] . '<br>';
    echo '<b>Name:</b> ' . $arr['customer_firstname'] . ' ' . $arr['customer_lastname'] . '<br>';
    echo '<b>@email:</b> ' . $arr['customer_email'] . '<br>';
    echo '<b>Status:</b> ' . $arr['status'] . '<br>';
    echo '<b>Created_at:</b> ' . $arr['created_at'] . '<br>';

    echo '<hr>';
}







// $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
// $orderDatamodel = $objectManager->get('Magento\Sales\Model\Order')->getCollection();
// foreach ($orderDatamodel as $orderDatamodel1) {
//     print_r($orderDatamodel1->getData());
// }


// $_orders = $block->getOrders();

// if ($_orders && count($_orders)) {
//     $complete = $pending = $closed = $canceled = $processing = $onHold = 0;
//     foreach ($_orders as $_order) {
//         $label = $_order->getStatusLabel();
//         switch ($label) {
//             case 'Complete':
//                 $complete++;
//                 break;
//             case 'Pending':
//                 $pending++;
//                 break;
//             case 'Processing':
//                 $processing++;
//                 break;
//             case 'Canceled':
//                 $canceled++;
//                 break;
//             case 'Closed':
//                 $closed++;
//                 break;
//         }
//     }
//     echo "<b>Order Status</b> <hr>";
//     echo "Completed Order - $complete <hr>";
//     echo "Pending Order - $pending  <hr>";
//     echo "Closed Order - $closed  <hr>";
//     echo "Canceled Order - $canceled <hr>";
//     echo "Processing Order - $processing <hr>";
// } else {
//     echo "You have no Orders";
// }
