<?php
/** @var \Perspective\CurrentProduct\Block\Index $block */
?>
<?php
    if ($currentProduct = $block->getCurrentProduct()) {
echo $currentProduct->getName() . '<br />';
echo $currentProduct->getSku() . '<br />';
echo $currentProduct->getFinalPrice() . '<br />';
echo $currentProduct->getProductUrl() . '<br />';
print_r ($currentProduct->getCategoryIds()) . '<br />';
}
// print current category data
if ($currentCategory = $block->getCurrentCategory()) {
echo $currentCategory->getName() . '<br />';
echo $currentCategory->getUrl() . '<br />';
}


 ?>
